# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitr', '0004_remove_applicant_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='recruiter',
        ),
    ]
