# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitr', '0010_auto_20171115_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
