# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitr', '0011_recruiter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='applicant.recruitr@gmail.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(default='recruiter.recruitr@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
